# -- Aplicación --
spring.application.name=gymsaas
server.port=8080

# -- Base de datos --
spring.datasource.url=jdbc:postgresql://localhost:5432/gymsaas
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# -- JPA / Hibernate --
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# -- Virtual Threads --
spring.threads.virtual.enabled=true

# -- JWT --
app.jwt.secret=7a4f2c8e1b9d3f6a0e5c7b2d4f8a1e3c6b9d2f5a8e1b4c7d0f3a6e9b2c5d8f1a4
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000