-- Catálogo de permisos
INSERT INTO permissions (id, code, description, module, created_at, updated_at) VALUES
    (gen_random_uuid(), 'MEMBER_VIEW',       'Ver socios',                'MEMBERS',     now(), now()),
    (gen_random_uuid(), 'MEMBER_CREATE',     'Crear socios',              'MEMBERS',     now(), now()),
    (gen_random_uuid(), 'MEMBER_EDIT',       'Editar socios',             'MEMBERS',     now(), now()),
    (gen_random_uuid(), 'MEMBER_CANCEL',     'Cancelar socios',           'MEMBERS',     now(), now()),
    (gen_random_uuid(), 'PLAN_VIEW',         'Ver planes',                'PLANS',       now(), now()),
    (gen_random_uuid(), 'PLAN_CREATE',       'Crear planes',              'PLANS',       now(), now()),
    (gen_random_uuid(), 'PLAN_EDIT',         'Editar planes',             'PLANS',       now(), now()),
    (gen_random_uuid(), 'PLAN_DEACTIVATE',   'Desactivar planes',         'PLANS',       now(), now()),
    (gen_random_uuid(), 'MEMBERSHIP_VIEW',   'Ver membresías',            'MEMBERSHIPS', now(), now()),
    (gen_random_uuid(), 'MEMBERSHIP_CREATE', 'Crear membresías',          'MEMBERSHIPS', now(), now()),
    (gen_random_uuid(), 'MEMBERSHIP_FREEZE', 'Congelar membresías',       'MEMBERSHIPS', now(), now()),
    (gen_random_uuid(), 'MEMBERSHIP_CANCEL', 'Cancelar membresías',       'MEMBERSHIPS', now(), now()),
    (gen_random_uuid(), 'PAYMENT_VIEW',      'Ver pagos',                 'PAYMENTS',    now(), now()),
    (gen_random_uuid(), 'PAYMENT_CREATE',    'Registrar pagos',           'PAYMENTS',    now(), now()),
    (gen_random_uuid(), 'PAYMENT_REFUND',    'Reembolsar pagos',          'PAYMENTS',    now(), now()),
    (gen_random_uuid(), 'BRANCH_VIEW',       'Ver sucursales',            'BRANCHES',    now(), now()),
    (gen_random_uuid(), 'BRANCH_CREATE',     'Crear sucursales',          'BRANCHES',    now(), now()),
    (gen_random_uuid(), 'BRANCH_EDIT',       'Editar sucursales',         'BRANCHES',    now(), now()),
    (gen_random_uuid(), 'BRANCH_DEACTIVATE', 'Desactivar sucursales',     'BRANCHES',    now(), now()),
    (gen_random_uuid(), 'USER_VIEW',         'Ver usuarios',              'USERS',       now(), now()),
    (gen_random_uuid(), 'USER_CREATE',       'Crear usuarios',            'USERS',       now(), now()),
    (gen_random_uuid(), 'USER_EDIT',         'Editar usuarios',           'USERS',       now(), now()),
    (gen_random_uuid(), 'ROLE_VIEW',         'Ver roles',                 'ROLES',       now(), now()),
    (gen_random_uuid(), 'ROLE_CREATE',       'Crear roles',               'ROLES',       now(), now()),
    (gen_random_uuid(), 'ROLE_EDIT',         'Editar roles y permisos',   'ROLES',       now(), now()),
    (gen_random_uuid(), 'DASHBOARD_VIEW',    'Ver dashboard',             'DASHBOARD',   now(), now()),
    (gen_random_uuid(), 'REPORT_VIEW',       'Ver reportes financieros',  'REPORTS',     now(), now())
ON CONFLICT (code) DO NOTHING;